config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'

  resources :movements do
  	get "order" => "movements#order"
  	collection do
	  	get "kiosk" => "movements#kiosk"
	  	get "foldback" => "movements#foldback"
	  	get "audience" => "movements#audience"
	  end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movement.rb
class Movement < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: %i[ show edit update destroy ]

  def kiosk
    @movements = Movement.all
  end

  def foldback
  end

  def audience
  end

  def order
    @movement = Movement.find(params[:movement_id])
    ActionCable.server.broadcast "orders_channel", message = (@movement)
  end

  # STANDARD ROUTES

  # GET /movements or /movements.json
  def index
    @movements = Movement.all
  end

  # GET /movements/1 or /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
    @movement.img_index = Movement.count + 4
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements or /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to movements_path, notice: "Movement was successfully created." }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1 or /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: "Movement was successfully updated." }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1 or /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: "Movement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movement_params
      params.require(:movement).permit(:name, :display_name, :img_index, :price, :time, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fiwar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movements/_form.html.erb
<%= form_with(model: movement) do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
        <% movement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :display_name %>
    <%= form.text_field :display_name %>
  </div>

  <div class="field">
    <%= form.label :img_index %>
    <%= form.number_field :img_index %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.number_field :time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movements/audience.html.erb
<div id="moves-list-container">
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-10"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-9"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-8"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-7"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-6"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-5"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-4"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-3"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-2"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-1"></span>
		</div>
		<div class="moves-list-item">
			<span class="moves-list-content" id="moves-list-0"></span>
		</div>
		<div class="moves-list-item" id="moves-list-item-active">
			<span class="moves-list-content" id="moves-list-active">No orders made yet</span>
		</div>
</div>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/foldback.html.erb
<div id="current-move-container">
		<span id="current-move">No Selection</span>
</div>
<div id="next-move-container">
	<span id="next-move">No Selection</span>
</div>
<div id="move-amount-container">
	<span id="move-amount">0</span>
</div>
<div id="sync-update-broadcaster"></div>

app/views/movements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movements</h1>

<%= link_to 'New Movement', new_movement_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Display name</th>
      <th>Image index</th>
      <th>Price</th>
      <th>Time</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= movement.name %></td>
        <td><%= movement.display_name %></td>
        <td><%= movement.img_index %></td>
        <td><%= movement.price %></td>
        <td><%= movement.time %></td>
        <td><%= movement.description %></td>
        <td><%= link_to 'Show', movement %></td>
        <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
        <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movements/kiosk.html.erb
<script src="/jquery-modal-min.js"></script>

<p id="notice" class="kiosk-notice"><%= notice %></p>

<div class="kiosk-header">
  <h1 class="kiosk-title">First it was a Rainforest</h1>
  <h4 class="kiosk-instructions">tap your selection to make an order</h4>
</div>

<div class="grid-container">
  <% @movements.each_with_index do |movement, i| %>
    <a href="#order-modal-<%= movement.id %>" rel="modal:open">
      <div class="grid-item"
      movement_id="<%= movement.id %>"
      movement_display_name="<%= movement.display_name %>">
        <% if ActionController::Base.helpers.resolve_asset_path("animations/#{movement.img_index}.gif") %>
          <%= image_tag "/assets/animations/#{movement.img_index}.gif", class: "grid-image img-selector-#{i%9}" %>
        <% else %>
          <%= image_tag "300px-#{(movement.img_index%12)+1}.png", class: "grid-image img-selector-#{i%9}" %>
        <% end %>
      </div>
    </a>
  <% end %>
</div>

<% @movements.each do |movement| %>
  <div id="order-modal-<%= movement.id %>" class="modal">
    <div class="modal-content">
      <span class="modal-order-line">You are ordering <b><%= movement.display_name %></b></span>
      <span class="modal-order-time">Our fulfilment team will begin delivering your order in approximately <span class="fulfillment-timer">5 seconds</span></span>
      <%= link_to "Confirm Order", movement_order_path(movement.id), remote: true, method: :get, class: "modal-order-link" %>
    </div>
  </div>
<% end %>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movement.name %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @movement.display_name %>
</p>

<p>
  <strong>Image index:</strong>
  <%= @movement.img_index %>
</p>

<p>
  <strong>Price:</strong>
  <%= @movement.price %>
</p>

<p>
  <strong>Time:</strong>
  <%= @movement.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movement.description %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>